version: '3.1'

services:
  api:
    image: python
    container_name: api-beers
    build: \api\Dockerfile
    ports:
      - 8000:5000
    depends_on:
      - db
    
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MY_SQL_DATABASE: beer
      container_name: db-beers