# Pour la BDD
version: '3.1'

services:

  db:
    image: mysql
    container_name: db-beers
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db-beers

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:5000