version: '3.1'

services:

  api:
    container_name: api-beers
    build: \api\Dockerfile
    ports:
      - 8000:8080
    depends_on:
      - db
    
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MY_SQL_DATABASE: beer
      container_name: db-beers